name: JoBase Wheels

on:
  workflow_dispatch:
    inputs:
      upload:
        description: Upload to PyPI
        required: true
        type: boolean

jobs:
  wheels:
    name: ${{matrix.os[1]}}
    runs-on: ${{matrix.os[0]}}

    strategy:
      matrix:
        os:
          - [macos-15-intel, MacOS Intel]
          # - [macos-latest, MacOS Silicon] done
          # - [windows-latest, Windows Intel] done
          # - [windows-11-arm, Windows ARM64] done
          - [ubuntu-latest, Linux Intel]
          - [ubuntu-24.04-arm, Linux Arm]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.13'
          # CIBW_ARCHS_MACOS: ${{runner.arch == 'X64' && 'x86_64' || 'arm64 universal2'}}
          CIBW_ARCHS_LINUX: ${{runner.arch == 'X64' && 'x86_64 i686 ppc64le s390x riscv64' || 'aarch64'}}
          CIBW_SKIP: 'cp3??t-*'
          #aarch64 armv7l

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl